## Understanding Numpy: External Library

In [3]:
import numpy as np

In [4]:
np_array = np.array([5,10,15,20,25,30])
np_array

array([ 5, 10, 15, 20, 25, 30])

In [5]:
print(np.unique(np_array))

[ 5 10 15 20 25 30]


In [6]:
print(np.std(np_array))

8.539125638299666


In [7]:
np_array.max()

30

In [8]:
np_array ** 2

array([ 25, 100, 225, 400, 625, 900])

In [9]:
np_array+np_array

array([10, 20, 30, 40, 50, 60])

In [10]:
np.sum(np_array**2)

2275

In [11]:
np_array.shape

(6,)

## Understanding Scipy: External library

In [12]:
from scipy import stats

In [13]:
array_1 = np.array([1,2,3,4,5,6])
array_2 = array_1

In [14]:
print(stats.pearsonr(array_1,array_2))

(0.9999999999999999, 1.8488927466117464e-32)
